### ISSUE TITLE
Matlab windows close in few seconds and then nothing happens

### ISSUE THREAD

**Issue by EliasGitHub** [schmidtchristoph/reach#10]
Hi Chris,

Thanks for your attempts to write down such an interesting library. I tried your package (reach) and also the other package which seems trying to develop a similar functionalities and I faced with the same problem. When I use the corresponding command to run a Matlab script (in this case obviously I'm talking about runMatlabScript) some windows open, presumably a Matlab console which seems that contain the results (even a figure with its plot) and then these windows close within very few seconds!!??

What should _I do to be able to run a Matlab script from R on MS Windows? I am using R version 3.3.2 through RStudio Version 1.0.136.

Thank you,
Elias

**Comment by EliasGitHub** [comment]
OOOPs,
Sorry man, I got it. As it is written in the manual (reach.pdf) this command _"executes the input Matlab script file (.m file) and quits Matlab"_
 
As you mentioned in the manual I can access this information (the outputs of the script) indirectly, it means by saving the results of the matlabs' script.

My apologies,
Elias

**Comment by schmidtchristoph** [comment]
Hi @EliasGitHub ,

No worries. Glad you figured it out. Let me know if you find issues - since I typically don't have much access to Windows machines the package is not as much tested there as it is for Linux or macOS.

**Comment by EliasGitHub** [comment]
Thanks for your attention. Another thing which is happening now is that my Matlab script takes a considerable amount of time to get finished with its calculations. Therefore I get some errors, when I call those results which are not published by Matlab yet. So the question is : How can I tell R to wait for Matlab script to be executed completely?  

I see it is not directly about reach package, but I wanted to ask you first, befor further googling.
Thank you so much again,
Elias

**Comment by schmidtchristoph** [comment]
@EliasGitHub Thanks for this piece of information. I can imagine that it has to do with Matlab being launched as a separate process (i.e. not within the R console) under Windows. On Linux or macOS R continues only after Matlab quits.

in ```runMatlabFct()``` I have this piece of code:

```
if(itswin){
      Sys.sleep(4) # for Windows only, wait until Matlab finished the computations - since Matlab process is separated from the running R session
      while(TRUE){
         if(file.exists(tmp_3)){ # returns TRUE, even if a large .mat file is still written and cannot be loaded (loading yields error 'Unknown data type)
            break

         } else {
            Sys.sleep(1.5)
         }
      }
   }
```

You could use something similar in your R script. Check for the presence of the .mat file with the results. You check for its existence with ```file.exists``` and break out of the while after Matlab finished the computations.


Another thing you might try is to modify the code of ```runMatlabScript``` to use the ```system2``` command instead of ```system```. Maybe this helps, I have no idea.

I made a note to look into this issue in the future. Currently, I am working a lot on other non-public projects. As soon as I can, I plan to resume to work on some other promised features for **reach**, as well as replacing ```system``` with ```system2``` and I will also see if I can do something about this issue. If you have any success with my suggestions, please let me know. If you have good modifications of the code, please open a pull request.

Hope this helps.

**Comment by EliasGitHub** [comment]
Thank you again Chris, it worked very well. I made a while loop with a break, checking whether the file exists or not. This is what I wrote in my R codes:

`while(TRUE){
  if(file.exists("my_results_matlab.csv")){
    break
  } else {
    Sys.sleep(2)
  }
 }`

**Comment by schmidtchristoph** [comment]
Great (-:!

Happy it worked for you.
Also, if the Matlab results file is going to be very large, it might be the case that the ```file.exists()``` can already see it before its writing has finished. In this case, it might be good to write a small temporary file after writing the big results file and checking for it instead.

Anyway, maybe I include this workaround in the respective **reach** function, i.e. I let the function write a copy of the input script file with appended writing of the temporary results file. 

Thank you for reporting back. Have a nice day!
